feat: SITES-9481 Initial implementation
adobe/franklin-json-ingestion-service pull request #10
Opened 2022-11-22 09:05 UTC by tyge68

Please ensure your pull request adheres to the following guidelines:
- [X] make sure to link the related issues in this description
- [X] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

see SITES-9481 (internal)

2022-11-22 09:36 UTC, tripodsan commented on src/index.js
> +const deleteItemAction = (s3, key, deletedKeys) => new Promise((resolve, reject) => {
why `Promise()` and not just `async` ?

2022-11-22 09:37 UTC, tripodsan commented on src/index.js
> +  params.Key = key;
this is kind of a weird pattern. better:

```suggestion
  const params = buildDefaultParams({
    Key: key,
  });
```

2022-11-22 09:38 UTC, tripodsan commented on src/index.js
> +      deletedKeys.push(params.Key);
this is ugly, adding the Key to a result array. why not just return it?

2022-11-22 09:39 UTC, tripodsan commented on src/index.js
> +const storeInPreview = async (s3, payload, options) => {
we prefer `function` style over the arrow pattern.

2022-11-22 09:39 UTC, tripodsan commented on src/index.js
> +const copyPreviewToLive = async (s3, options) => {
we prefer `function` style over the arrow pattern.

2022-11-22 09:40 UTC, tripodsan commented on src/index.js
> +  params.CopySource = encodeURI(`${params.Bucket}/${options.s3SourceObjectPath}${options.suffix}.json`);
are you sure this needs to be encoded ?

2022-11-22 09:40 UTC, tripodsan commented on src/index.js
> +const evictFromS3 = async (s3, s3ObjectPath) => {
we prefer `function` style over the arrow pattern.

2022-11-22 09:41 UTC, tripodsan commented on src/index.js
> +    const listResponse = await s3.send(new ListObjectsCommand(params));
this is not sufficient, the ListObjectCommand might only return the default paging size object.
see https://github.com/adobe/helix-admin/blob/965d46b14e33207f810db438dd534145481b43a4/src/support/storage.js#L347-L368 for an example for reading all results.

2022-11-22 09:43 UTC, tripodsan commented on src/index.js
> +    await Promise.all(promises);
better use https://github.com/adobe/helix-shared/tree/main/packages/helix-shared-process-queue

2022-11-22 09:45 UTC, tripodsan commented on src/index.js
> +      const variation = json.variation || 'master';
`master` is a politically incorrect terminology. use `main` instead.

2022-11-22 10:05 UTC, tripodsan commented on src/index.js
> +  params.CopySource = encodeURI(`${params.Bucket}/${options.s3SourceObjectPath}${options.suffix}.json`);
ah right: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/copyobjectcommandinput.html#copysource

2022-11-22 10:05 UTC, tyge68 commented on src/index.js
> +      const variation = json.variation || 'master';
sorry but content fragment still use master as the naming convention, so main would be wrong here

2022-11-22 16:03 UTC, tripodsan requested changes
LGTM, only some minor details.

2022-11-22 16:03 UTC, tripodsan commented on src/storage.js
> +}
simpler to use promisify:

```js
import { promisify } from 'util';
import zlib from 'zlib';
.
.
const gzip = promisify(zlib.gzip);
const gunzip = promisify(zlib.gunzip);
```

2022-11-22 16:03 UTC, tripodsan commented on src/storage.js
> +  buildDefaultParams(options) {
```suggestion
  buildDefaultParams(options = {}) {
```

2022-11-23 21:53 UTC, tripodsan approved these changes
perfect. thanks!

2022-11-24 07:18 UTC, merged