feat: SITES-9963 adding invalidate cache logic
adobe/franklin-json-ingestion-service pull request #26
Opened 2023-01-17 14:13 UTC by tyge68

Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues
SITES-9963 In order to demo the full flow , it need to send a cache invalidation to cloudflare

Thanks for contributing!

2023-02-06 09:02 UTC, tyge68 commented
@tripodsan could you check this change, then let me know if I can merge it to use a stable url on Odin QA (and soon Odin Prod)

2023-02-17 08:18 UTC, tripodsan commented on src/request-util.js
> +      }
but this is not correct. when the content-type is json, it must not be base64 encoded and zipped.
also, why not sending binary data? base64 makes the payload 20% larger.
If you want to support zipped payloads, I would keep the content-type app/json, but support transport-encoding: gzip. this way it's all nicely abstracted via the http protocol.

2023-02-17 08:20 UTC, tripodsan commented on src/request-util.js
> +    if (this.request.headers.get('Content-Type') !== APPLICATION_JSON) {
this check is very strict, eg in respect to whitespaces. I would do `startsWith(...)`.

2023-02-17 08:20 UTC, tripodsan requested changes
don't confuse the API user with weird payload handling

2023-02-17 08:28 UTC, tyge68 commented on src/request-util.js
> +      }
@tripodsan make sense I will check if that can be done / tested also.

2023-02-17 14:04 UTC, tripodsan commented on src/request-util.js
> +    if (!this.request.headers.get('Content-Type').startsWith(APPLICATION_JSON)) {
but now this is wrong. if should only startWith(`application/json`) not with the encoding

2023-02-17 14:33 UTC, merged

2023-02-17 15:04 UTC, tripodsan commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on:
- `v1.5.0`
- `v1.5.0`
- [GitHub release](https://github.com/adobe/franklin-json-ingestion-service/releases/tag/v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: